import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import { withPageAuthRequired } from "@auth0/nextjs-auth0";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </UserProvider>
    </html>
  );
}

export default withPageAuthRequired(RootLayout);
